### YamlMime:ManagedReference
items:
- uid: Sorted.PRO.SDK.Security
  commentId: N:Sorted.PRO.SDK.Security
  id: Sorted.PRO.SDK.Security
  children:
  - Sorted.PRO.SDK.Security.RoleService
  - Sorted.PRO.SDK.Security.SecurityService
  langs:
  - csharp
  - vb
  name: Sorted.PRO.SDK.Security
  nameWithType: Sorted.PRO.SDK.Security
  fullName: Sorted.PRO.SDK.Security
  type: Namespace
  assemblies:
  - Sorted.PRO.SDK.Security
references:
- uid: Sorted.PRO.SDK.Security.RoleService
  commentId: T:Sorted.PRO.SDK.Security.RoleService
  name: RoleService
  nameWithType: RoleService
  fullName: Sorted.PRO.SDK.Security.RoleService
- uid: Sorted.PRO.SDK.Security.SecurityService
  commentId: T:Sorted.PRO.SDK.Security.SecurityService
  name: SecurityService
  nameWithType: SecurityService
  fullName: Sorted.PRO.SDK.Security.SecurityService
