### YamlMime:ManagedReference
items:
- uid: Sorted.PRO.SDK.Interfaces.Security
  commentId: N:Sorted.PRO.SDK.Interfaces.Security
  id: Sorted.PRO.SDK.Interfaces.Security
  children:
  - Sorted.PRO.SDK.Interfaces.Security.IRoleService
  - Sorted.PRO.SDK.Interfaces.Security.ISecurityService
  langs:
  - csharp
  - vb
  name: Sorted.PRO.SDK.Interfaces.Security
  nameWithType: Sorted.PRO.SDK.Interfaces.Security
  fullName: Sorted.PRO.SDK.Interfaces.Security
  type: Namespace
  assemblies:
  - Sorted.PRO.SDK.Interfaces.Security
references:
- uid: Sorted.PRO.SDK.Interfaces.Security.IRoleService
  commentId: T:Sorted.PRO.SDK.Interfaces.Security.IRoleService
  parent: Sorted.PRO.SDK.Interfaces.Security
  name: IRoleService
  nameWithType: IRoleService
  fullName: Sorted.PRO.SDK.Interfaces.Security.IRoleService
- uid: Sorted.PRO.SDK.Interfaces.Security.ISecurityService
  commentId: T:Sorted.PRO.SDK.Interfaces.Security.ISecurityService
  parent: Sorted.PRO.SDK.Interfaces.Security
  name: ISecurityService
  nameWithType: ISecurityService
  fullName: Sorted.PRO.SDK.Interfaces.Security.ISecurityService
- uid: Sorted.PRO.SDK.Interfaces.Security
  commentId: N:Sorted.PRO.SDK.Interfaces.Security
  name: Sorted.PRO.SDK.Interfaces.Security
  nameWithType: Sorted.PRO.SDK.Interfaces.Security
  fullName: Sorted.PRO.SDK.Interfaces.Security
