### YamlMime:ManagedReference
items:
- uid: Sorted.PRO.SDK.DataTypes.Security
  commentId: N:Sorted.PRO.SDK.DataTypes.Security
  id: Sorted.PRO.SDK.DataTypes.Security
  children:
  - Sorted.PRO.SDK.DataTypes.Security.Access
  - Sorted.PRO.SDK.DataTypes.Security.AuthenticateResponse
  - Sorted.PRO.SDK.DataTypes.Security.BasicCarrierServiceGroup
  - Sorted.PRO.SDK.DataTypes.Security.BasicRole
  - Sorted.PRO.SDK.DataTypes.Security.Permission
  - Sorted.PRO.SDK.DataTypes.Security.PermissionGroup
  - Sorted.PRO.SDK.DataTypes.Security.Role
  - Sorted.PRO.SDK.DataTypes.Security.ValidateTokenRequest
  langs:
  - csharp
  - vb
  name: Sorted.PRO.SDK.DataTypes.Security
  nameWithType: Sorted.PRO.SDK.DataTypes.Security
  fullName: Sorted.PRO.SDK.DataTypes.Security
  type: Namespace
  assemblies:
  - Sorted.PRO.SDK.DataTypes.Security
references:
- uid: Sorted.PRO.SDK.DataTypes.Security.Access
  commentId: T:Sorted.PRO.SDK.DataTypes.Security.Access
  parent: Sorted.PRO.SDK.DataTypes.Security
  name: Access
  nameWithType: Access
  fullName: Sorted.PRO.SDK.DataTypes.Security.Access
- uid: Sorted.PRO.SDK.DataTypes.Security.AuthenticateResponse
  commentId: T:Sorted.PRO.SDK.DataTypes.Security.AuthenticateResponse
  name: AuthenticateResponse
  nameWithType: AuthenticateResponse
  fullName: Sorted.PRO.SDK.DataTypes.Security.AuthenticateResponse
- uid: Sorted.PRO.SDK.DataTypes.Security.BasicCarrierServiceGroup
  commentId: T:Sorted.PRO.SDK.DataTypes.Security.BasicCarrierServiceGroup
  name: BasicCarrierServiceGroup
  nameWithType: BasicCarrierServiceGroup
  fullName: Sorted.PRO.SDK.DataTypes.Security.BasicCarrierServiceGroup
- uid: Sorted.PRO.SDK.DataTypes.Security.BasicRole
  commentId: T:Sorted.PRO.SDK.DataTypes.Security.BasicRole
  name: BasicRole
  nameWithType: BasicRole
  fullName: Sorted.PRO.SDK.DataTypes.Security.BasicRole
- uid: Sorted.PRO.SDK.DataTypes.Security.Permission
  commentId: T:Sorted.PRO.SDK.DataTypes.Security.Permission
  name: Permission
  nameWithType: Permission
  fullName: Sorted.PRO.SDK.DataTypes.Security.Permission
- uid: Sorted.PRO.SDK.DataTypes.Security.PermissionGroup
  commentId: T:Sorted.PRO.SDK.DataTypes.Security.PermissionGroup
  name: PermissionGroup
  nameWithType: PermissionGroup
  fullName: Sorted.PRO.SDK.DataTypes.Security.PermissionGroup
- uid: Sorted.PRO.SDK.DataTypes.Security.Role
  commentId: T:Sorted.PRO.SDK.DataTypes.Security.Role
  parent: Sorted.PRO.SDK.DataTypes.Security
  name: Role
  nameWithType: Role
  fullName: Sorted.PRO.SDK.DataTypes.Security.Role
- uid: Sorted.PRO.SDK.DataTypes.Security.ValidateTokenRequest
  commentId: T:Sorted.PRO.SDK.DataTypes.Security.ValidateTokenRequest
  name: ValidateTokenRequest
  nameWithType: ValidateTokenRequest
  fullName: Sorted.PRO.SDK.DataTypes.Security.ValidateTokenRequest
- uid: Sorted.PRO.SDK.DataTypes.Security
  commentId: N:Sorted.PRO.SDK.DataTypes.Security
  name: Sorted.PRO.SDK.DataTypes.Security
  nameWithType: Sorted.PRO.SDK.DataTypes.Security
  fullName: Sorted.PRO.SDK.DataTypes.Security
