### YamlMime:ManagedReference
items:
- uid: Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType
  commentId: T:Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType
  id: ApplicationType
  parent: Sorted.PRO.SDK.DataTypes.Rates.Enums
  children:
  - Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType.Retrospective
  - Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType.Standard
  - Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType.Unknown
  langs:
  - csharp
  - vb
  name: ApplicationType
  nameWithType: ApplicationType
  fullName: Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType
  type: Enum
  source:
    remote:
      path: Sorted.PRO.SDK.DataTypes.Rates/Enums/ApplicationType..cs
      branch: doc-comments
      repo: git@bitbucket.org:mpdelectio/sorted.pro.sdk.git
    id: ApplicationType
    path: ../../sorted.pro.sdk/Sorted.PRO.SDK.DataTypes.Rates/Enums/ApplicationType..cs
    startLine: 7
  assemblies:
  - Sorted.PRO.SDK.DataTypes.Rates
  namespace: Sorted.PRO.SDK.DataTypes.Rates.Enums
  syntax:
    content: >-
      [DataContract]

      [DataContractType("Application Type", "Determines the application type for a surcharge.")]

      [Serializable]

      public enum ApplicationType : short
    content.vb: >-
      <DataContract>

      <DataContractType("Application Type", "Determines the application type for a surcharge.")>

      <Serializable>

      Public Enum ApplicationType As Short
  attributes:
  - type: System.Runtime.Serialization.DataContractAttribute
    ctor: System.Runtime.Serialization.DataContractAttribute.#ctor
    arguments: []
  - type: Sorted.PRO.SDK.Shared.Attributes.Documentation.DataContractType
    ctor: Sorted.PRO.SDK.Shared.Attributes.Documentation.DataContractType.#ctor(System.String,System.String)
    arguments:
    - type: System.String
      value: Application Type
    - type: System.String
      value: Determines the application type for a surcharge.
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType.Unknown
  commentId: F:Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType.Unknown
  id: Unknown
  parent: Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType
  langs:
  - csharp
  - vb
  name: Unknown
  nameWithType: ApplicationType.Unknown
  fullName: Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType.Unknown
  type: Field
  source:
    remote:
      path: Sorted.PRO.SDK.DataTypes.Rates/Enums/ApplicationType..cs
      branch: doc-comments
      repo: git@bitbucket.org:mpdelectio/sorted.pro.sdk.git
    id: Unknown
    path: ../../sorted.pro.sdk/Sorted.PRO.SDK.DataTypes.Rates/Enums/ApplicationType..cs
    startLine: 13
  assemblies:
  - Sorted.PRO.SDK.DataTypes.Rates
  namespace: Sorted.PRO.SDK.DataTypes.Rates.Enums
  syntax:
    content: Unknown = 0
    return:
      type: Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType.Standard
  commentId: F:Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType.Standard
  id: Standard
  parent: Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType
  langs:
  - csharp
  - vb
  name: Standard
  nameWithType: ApplicationType.Standard
  fullName: Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType.Standard
  type: Field
  source:
    remote:
      path: Sorted.PRO.SDK.DataTypes.Rates/Enums/ApplicationType..cs
      branch: doc-comments
      repo: git@bitbucket.org:mpdelectio/sorted.pro.sdk.git
    id: Standard
    path: ../../sorted.pro.sdk/Sorted.PRO.SDK.DataTypes.Rates/Enums/ApplicationType..cs
    startLine: 14
  assemblies:
  - Sorted.PRO.SDK.DataTypes.Rates
  namespace: Sorted.PRO.SDK.DataTypes.Rates.Enums
  syntax:
    content: >-
      [EnumMember]

      Standard = 1
    return:
      type: Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType
    content.vb: >-
      <EnumMember>

      Standard = 1
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType.Retrospective
  commentId: F:Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType.Retrospective
  id: Retrospective
  parent: Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType
  langs:
  - csharp
  - vb
  name: Retrospective
  nameWithType: ApplicationType.Retrospective
  fullName: Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType.Retrospective
  type: Field
  source:
    remote:
      path: Sorted.PRO.SDK.DataTypes.Rates/Enums/ApplicationType..cs
      branch: doc-comments
      repo: git@bitbucket.org:mpdelectio/sorted.pro.sdk.git
    id: Retrospective
    path: ../../sorted.pro.sdk/Sorted.PRO.SDK.DataTypes.Rates/Enums/ApplicationType..cs
    startLine: 16
  assemblies:
  - Sorted.PRO.SDK.DataTypes.Rates
  namespace: Sorted.PRO.SDK.DataTypes.Rates.Enums
  syntax:
    content: >-
      [EnumMember]

      Retrospective = 2
    return:
      type: Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType
    content.vb: >-
      <EnumMember>

      Retrospective = 2
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Sorted.PRO.SDK.DataTypes.Rates.Enums
  commentId: N:Sorted.PRO.SDK.DataTypes.Rates.Enums
  name: Sorted.PRO.SDK.DataTypes.Rates.Enums
  nameWithType: Sorted.PRO.SDK.DataTypes.Rates.Enums
  fullName: Sorted.PRO.SDK.DataTypes.Rates.Enums
- uid: Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType
  commentId: T:Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType
  parent: Sorted.PRO.SDK.DataTypes.Rates.Enums
  name: ApplicationType
  nameWithType: ApplicationType
  fullName: Sorted.PRO.SDK.DataTypes.Rates.Enums.ApplicationType
