### YamlMime:ManagedReference
items:
- uid: Sorted.PRO.SDK.Interfaces.Settings
  commentId: N:Sorted.PRO.SDK.Interfaces.Settings
  id: Sorted.PRO.SDK.Interfaces.Settings
  children:
  - Sorted.PRO.SDK.Interfaces.Settings.ICarrierServiceService
  - Sorted.PRO.SDK.Interfaces.Settings.ICarriersService
  - Sorted.PRO.SDK.Interfaces.Settings.ICollectionCalendarService
  - Sorted.PRO.SDK.Interfaces.Settings.IPackageSizeService
  - Sorted.PRO.SDK.Interfaces.Settings.IServiceGroupsService
  - Sorted.PRO.SDK.Interfaces.Settings.IShippingLocationsService
  - Sorted.PRO.SDK.Interfaces.Settings.IStaticDataService
  langs:
  - csharp
  - vb
  name: Sorted.PRO.SDK.Interfaces.Settings
  nameWithType: Sorted.PRO.SDK.Interfaces.Settings
  fullName: Sorted.PRO.SDK.Interfaces.Settings
  type: Namespace
  assemblies:
  - Sorted.PRO.SDK.Interfaces.Settings
references:
- uid: Sorted.PRO.SDK.Interfaces.Settings.ICarrierServiceService
  commentId: T:Sorted.PRO.SDK.Interfaces.Settings.ICarrierServiceService
  parent: Sorted.PRO.SDK.Interfaces.Settings
  name: ICarrierServiceService
  nameWithType: ICarrierServiceService
  fullName: Sorted.PRO.SDK.Interfaces.Settings.ICarrierServiceService
- uid: Sorted.PRO.SDK.Interfaces.Settings.ICarriersService
  commentId: T:Sorted.PRO.SDK.Interfaces.Settings.ICarriersService
  parent: Sorted.PRO.SDK.Interfaces.Settings
  name: ICarriersService
  nameWithType: ICarriersService
  fullName: Sorted.PRO.SDK.Interfaces.Settings.ICarriersService
- uid: Sorted.PRO.SDK.Interfaces.Settings.ICollectionCalendarService
  commentId: T:Sorted.PRO.SDK.Interfaces.Settings.ICollectionCalendarService
  parent: Sorted.PRO.SDK.Interfaces.Settings
  name: ICollectionCalendarService
  nameWithType: ICollectionCalendarService
  fullName: Sorted.PRO.SDK.Interfaces.Settings.ICollectionCalendarService
- uid: Sorted.PRO.SDK.Interfaces.Settings.IPackageSizeService
  commentId: T:Sorted.PRO.SDK.Interfaces.Settings.IPackageSizeService
  parent: Sorted.PRO.SDK.Interfaces.Settings
  name: IPackageSizeService
  nameWithType: IPackageSizeService
  fullName: Sorted.PRO.SDK.Interfaces.Settings.IPackageSizeService
- uid: Sorted.PRO.SDK.Interfaces.Settings.IServiceGroupsService
  commentId: T:Sorted.PRO.SDK.Interfaces.Settings.IServiceGroupsService
  parent: Sorted.PRO.SDK.Interfaces.Settings
  name: IServiceGroupsService
  nameWithType: IServiceGroupsService
  fullName: Sorted.PRO.SDK.Interfaces.Settings.IServiceGroupsService
- uid: Sorted.PRO.SDK.Interfaces.Settings.IShippingLocationsService
  commentId: T:Sorted.PRO.SDK.Interfaces.Settings.IShippingLocationsService
  parent: Sorted.PRO.SDK.Interfaces.Settings
  name: IShippingLocationsService
  nameWithType: IShippingLocationsService
  fullName: Sorted.PRO.SDK.Interfaces.Settings.IShippingLocationsService
- uid: Sorted.PRO.SDK.Interfaces.Settings.IStaticDataService
  commentId: T:Sorted.PRO.SDK.Interfaces.Settings.IStaticDataService
  parent: Sorted.PRO.SDK.Interfaces.Settings
  name: IStaticDataService
  nameWithType: IStaticDataService
  fullName: Sorted.PRO.SDK.Interfaces.Settings.IStaticDataService
- uid: Sorted.PRO.SDK.Interfaces.Settings
  commentId: N:Sorted.PRO.SDK.Interfaces.Settings
  name: Sorted.PRO.SDK.Interfaces.Settings
  nameWithType: Sorted.PRO.SDK.Interfaces.Settings
  fullName: Sorted.PRO.SDK.Interfaces.Settings
