### YamlMime:ManagedReference
items:
- uid: Sorted.PRO.SDK.Settings
  commentId: N:Sorted.PRO.SDK.Settings
  id: Sorted.PRO.SDK.Settings
  children:
  - Sorted.PRO.SDK.Settings.CarrierServiceService
  - Sorted.PRO.SDK.Settings.CarriersService
  - Sorted.PRO.SDK.Settings.CollectionCalendarService
  - Sorted.PRO.SDK.Settings.PackageSizeService
  - Sorted.PRO.SDK.Settings.ServiceGroupsService
  - Sorted.PRO.SDK.Settings.ShippingLocationsServiceService
  - Sorted.PRO.SDK.Settings.StaticDataService
  langs:
  - csharp
  - vb
  name: Sorted.PRO.SDK.Settings
  nameWithType: Sorted.PRO.SDK.Settings
  fullName: Sorted.PRO.SDK.Settings
  type: Namespace
  assemblies:
  - Sorted.PRO.SDK.Settings
references:
- uid: Sorted.PRO.SDK.Settings.CarrierServiceService
  commentId: T:Sorted.PRO.SDK.Settings.CarrierServiceService
  name: CarrierServiceService
  nameWithType: CarrierServiceService
  fullName: Sorted.PRO.SDK.Settings.CarrierServiceService
- uid: Sorted.PRO.SDK.Settings.CarriersService
  commentId: T:Sorted.PRO.SDK.Settings.CarriersService
  name: CarriersService
  nameWithType: CarriersService
  fullName: Sorted.PRO.SDK.Settings.CarriersService
- uid: Sorted.PRO.SDK.Settings.CollectionCalendarService
  commentId: T:Sorted.PRO.SDK.Settings.CollectionCalendarService
  name: CollectionCalendarService
  nameWithType: CollectionCalendarService
  fullName: Sorted.PRO.SDK.Settings.CollectionCalendarService
- uid: Sorted.PRO.SDK.Settings.PackageSizeService
  commentId: T:Sorted.PRO.SDK.Settings.PackageSizeService
  name: PackageSizeService
  nameWithType: PackageSizeService
  fullName: Sorted.PRO.SDK.Settings.PackageSizeService
- uid: Sorted.PRO.SDK.Settings.ServiceGroupsService
  commentId: T:Sorted.PRO.SDK.Settings.ServiceGroupsService
  name: ServiceGroupsService
  nameWithType: ServiceGroupsService
  fullName: Sorted.PRO.SDK.Settings.ServiceGroupsService
- uid: Sorted.PRO.SDK.Settings.ShippingLocationsServiceService
  commentId: T:Sorted.PRO.SDK.Settings.ShippingLocationsServiceService
  name: ShippingLocationsServiceService
  nameWithType: ShippingLocationsServiceService
  fullName: Sorted.PRO.SDK.Settings.ShippingLocationsServiceService
- uid: Sorted.PRO.SDK.Settings.StaticDataService
  commentId: T:Sorted.PRO.SDK.Settings.StaticDataService
  name: StaticDataService
  nameWithType: StaticDataService
  fullName: Sorted.PRO.SDK.Settings.StaticDataService
